### ISSUE TITLE
Add an option to use ZeroCopy Protobuf techniques for puts

### ISSUE THREAD

**Issue by sduskis** [googleapis/java-bigtable-hbase#1205]
Gets and Scans use a technique to pull byte[] out of protobuf objects without copying the underlying byte[], which is standard practice with protobuf.  That improves performance.  We should provide an option to wrap byte[] that come from Puts and other mutations.

**Comment by rahulKQL** [comment]
We are using `UnsafeByteOperation#unsafeWrap` in [ZeroCopyByteStringUtil.java](https://github.com/googleapis/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/util/ZeroCopyByteStringUtil.java#L44-L46). 
when below check fails then we are defaulting to `ByteString#copyFrom`in [ByteStringer](https://github.com/googleapis/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/util/ByteStringer.java#L32-L39),
```java
  static {
    try {
      ZeroCopyByteStringUtil.wrap(new byte[0]);
    } catch (IllegalAccessError iae) {
      USE_ZEROCOPYBYTESTRING = false;
      LOG.debug("Failed to classload BigtableZeroCopyByteString: " + iae.toString());
    }
  }
```
Now that we are dependent on `google-cloud-bigtable`([Issue 5030](https://github.com/googleapis/google-cloud-java/issues/5030#issue-437872925)), is it still ok to use this Util for Put & mutate operations?

**Comment by sduskis** [comment]
Using `ZeroCopyByteStringUtil` could provide a significant performance improvements for `Put`.  It has provided 10X improvements for reads.  What failure did you see?

**Comment by rahulKQL** [comment]
I don't see any failures, It's just that I thought of using the same utility for Put & mutate operations, So asked for your opinion before starting on that change.

**Comment by igorbernstein2** [comment]
So the underlying issue the ejona86 wants to prevent is diamond dependency problems when 2 subdependencies depend on 2 incompatible surfaces of sub-sub-dependencies. The hbase client has 3 artifacts:
1. default - which uses hbase-shaded-client and exposes all of the internal dependencies of the -core client
2. hadoop - which inverts default: all of the internal dependencies of -core are shaded and the hadoop deps are public
3. shaded - everything is shaded

default was necessary because this was our only java client and we needed deps that would be compatible with other google clients. Once gcj goes GA this is no longer necessary. At that point the only reason a customer would want to use the hbase api is to be backwards compatible with hbase, which means that their deps should also be hbase/hadoop compatible. So at some point in the future I intend to remove the default artifact and make the hadoop artifact the default one.

This means that the hbase client will not be in danger of diamond dependency issues. So I think it's ok to use our dependency's experimental apis
