### ISSUE TITLE
Throttle read RPC

### ISSUE THREAD

**Issue by simeg** [googleapis/java-bigtable-hbase#2173]
There's [throttling options](https://github.com/googleapis/cloud-bigtable-client/blob/70ef7dbc0d816887191e54b584cfaacda14f9555/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/config/BulkOptions.java#L96) available for bulk mutation RPC. Are there any plans for implementing a throttle option for reading? If there are none - how much of an effort would it be for someone else, like myself, to implement the feature?

**Comment by sduskis** [comment]
What's the use case you had in mind for reading?

Some background: 

Bulk mutations have an application in batch jobs.  Batch write jobs are really efficient and can easily push a Cloud Bigtable Cluster to its limit.  Writes also are "unary RPCs" with a single request / response model, so there was a place where the client could measure the health of the service by measuring RPC response times; that "measure of health" is used to slow down RPCs if the service responds slowly.

Cloud Bigtable is really efficient at reading sequential rows, and it's difficult to bring down a service with a batch job that reads an entire table.  Reads are "streaming RPCs", and there isn't a simple way to get a proxy for service health like there is with Writes.

**Comment by simeg** [comment]
Thanks for the background.

We use dataflow jobs to read from BT at scale and we sometimes face issues with BT not being able to auto-scale fast enough to keep up with the auto-scaling dataflow jobs, causing them to stop (a theory we have). One idea we had was to implement throttling in the dataflow job but I wanted to start here to see if I could learn more.

Does that answer your question? Thanks.

**Comment by bshafiee** [comment]
@simeg did you figure out any solution? We face the same problem, cloud dataflow can very well bringdown a bigtable cluster with its table scans. What I've been doing is to limit auto scaling in dataflow to a lowerbound which won't break our bigtable cluster but that's annoying since after we read rows from bigtable we can use way more nodes and our job takes more than it should since we can't increase the limit afterwards. I described the situation here too:  https://stackoverflow.com/questions/58565633/dynamically-scale-cloud-dataflow-job?noredirect=1#comment103500714_58565633 but no solution.

**Comment by simeg** [comment]
@bshafiee No we did not come up with a good solution. We've also tweaked dataflow (limit the amount of threads for example) and tweaked auto-scaling settings for BigTable. We still have this issue.

**Comment by govindaraj-indihood** [comment]
Dataflow reading from Bigtable appears to quickly push Bigtable CPU usage over 90%. We're looking for a solution to throttle dataflow streaming reads
