### ISSUE TITLE
Unclear if we are matching functionality for FirstKeyOnlyFilter

### ISSUE THREAD

**Issue by billyjacobson** [googleapis/java-bigtable-hbase#2477]
Can we add a check to this test that sees if the row data is returned by HBase's FirstKeyOnlyFilter and if so, we should potentially change the Bigtable HBase client's FirstKeyOnlyFilter to act in the same way. 

https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java#L1381

**Comment by rahulKQL** [comment]
Hi @billyjacobson 

I think [HBase's FirstKeyOnlyFilter](https://github.com/apache/hbase/blob/branch-2.3/hbase-client/src/main/java/org/apache/hadoop/hbase/filter/FirstKeyOnlyFilter.java#L33-L39) should return the first KV for the rows it matches. Our FirstKeyOnlyFilterAdapter has the same filter condition:
https://github.com/googleapis/java-bigtable-hbase/blob/7b2d0df5a3ebc7da35c5193bcd697ab5e92c2d00/bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/FirstKeyOnlyFilterAdapter.java#L30-L33

For more clarity, I have updated the mentioned test case to perform a scan instead of point read. Please let me know if I am missing something.

**Comment by billyjacobson** [comment]
My comment was that HBase says it returns the first KV pair but ours returns only the first key because we strip out the value. It says that in their documentation here: https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/filter/FirstKeyOnlyFilter.html

I'm not sure if I am misinterpreting the documentation, so I think we should check if there is a value returned (rather than just the key) and make sure we are doing the same thing.

**Comment by rahulKQL** [comment]
@billyjacobson Thanks for the explanation!! Indeed HBase returns value along with the first column details.
It seems this change was intentionally done via #1989 for performance improvement. I am not sure what should be our priority here.

@igorbernstein2 / @kolea2 Please let us know how should we proceed here.

**Comment by igorbernstein2** [comment]
I think we need to revert that PR. We should stay consistent with HBase rather then try to optimize it. Sorry for creating this issue

**Comment by billyjacobson** [comment]
I think we should have a filter that does what it currently does though. It could go by another name, but I think it would be very useful to have when counting rows. We recommend that people use this filter for that and if it is retrieving the data for even a single column, it could send a ton more data.

**Comment by igorbernstein2** [comment]
Shouldnt we recommend people to use https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/filter/KeyOnlyFilter.html for that?

**Comment by billyjacobson** [comment]
Oh that could work!
